### ISSUE TITLE
Why use ME-GraphAU in GCN part?

### ISSUE THREAD

**Issue by liuxing007** [TaatiTeam/MotionAGFormer#32]
I appreciate for your great work! I have some questions, please give us some help ,thx!

Why did you consider using ME-GraphAU? Have you compared it with other GCN methods
Also, we want to train and test on 2D ground truth. How should we train for that?

**Comment by SoroushMehraban** [comment]
Hi @liuxing007 ,
Thank you for the interest. For the temporal part of the GCN branch, the usual thing to try is the TCN that usually people use. I was interested to model it with GCNFormer instead but I didn't know which node should be connected to which node. For spatial branch it was obvious. I could use physically connected edges (shoulders to elbows, elbows to wrists, etc.). For temporal part a naive solution could be just using next frame and the previous frame. So for example the wrist joint at frame 100 would be connected to itself at frame 99 and 101 and the wrist at frame 99 would be connected to 98 and 100.

And we can consider GCNs as information passing between the nodes (See my [GCN video](https://youtu.be/eLcGehfjvgs?si=grUI-_-tCGXcYDve) for more details). So I thought what if the node at the at a frame distant away is more useful for information passing compared to the exact next frame and previous frame. That's why I used a method similar to ME-GraphAU to make it learnable and model decides which node to select for the information passing.

As for your next question, see [issue 31](https://github.com/TaatiTeam/MotionAGFormer/issues/31#issuecomment-2027910013) for the answer.
