### ISSUE TITLE
The evaluation of MotionAGFormer-L with GT 2D points as input.

### ISSUE THREAD

**Issue by poker-xu** [TaatiTeam/MotionAGFormer#62]
Thank you for your great work. We would like to evaluate the MPJPE metric of MotionAGFormer-L with GT 2D points as input, and I was wondering if you could provide the weights corresponding to an MPJPE of 17.3. Thanks！

**Comment by SoroushMehraban** [comment]
@poker-xu Sorry but I'm afraid the I removed the checkpoints of that due to shortage of space. In case you're needing that because of using it in a application, note that it is trained when the **2D pose sequence as input is perfect and has no estimation noise**, which is achieved by projecting 3D points into 2D. Although the model achieves a better performance, it should generally be worse at inference time since once you give it 2D pose as input, it is estimated from a 2D estimator that is noisy but the model is not robust against noise since it hasn't seen noisy 2D pose throughout training.
