### ISSUE TITLE
3D pose result

### ISSUE THREAD

**Issue by zh199110** [TaatiTeam/MotionAGFormer#9]
Hello,I want to ask a question? Tesing in the wild video,how to verify the  result of 3D pose is right when are no GT? When  different scene data is tested , the result wether is related to the camera parameters?

**Comment by SoroushMehraban** [comment]
@zh199110 It's not possible to quantitatively verify the result as we don't have any GT and we can only qualitatively observe and compare with other works. Note that as I explained in #8, since we're dealing with an ill-posed problem, reconstruction of output in millimeters from a monocular camera is not possible when only 2D pose sequence is received as input.
